services:
  portal:
    build:
      context: .
      args:
        - VITE_API_URL=https://portal.ajanstek.com/api
    image: portal-app
    container_name: portal-app
    environment:
      - PORT=3000
      - NODE_ENV=production
      - CHROME_PATH=/usr/bin/google-chrome-stable
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - PORTAL_URL=https://portal.ajanstek.com
    volumes:
      - ./data:/app/data
      - ./public/screenshots:/app/public/screenshots
    ports:
      - "3000:3000"
    restart: always
